---
title: "Privacy Policy"
format: html
---

Your privacy is important to us. This policy outlines how this website collects, uses, and protects your information.

## Information Collection and Use

We use Google Analytics, a web analytics service provided by Google, LLC. (“Google”). Google Analytics uses cookies to help analyze how people interact with this content, including tracking which sections are accessed most frequently. Information generated by cookies about your use of our website (including IP address) will be transmitted to and stored by Google on servers in the United States.

Google will use this information solely for evaluating webpage usage, compiling usage reports to enhance the educational effectiveness of the content, and providing related services.

You may refuse the use of cookies by selecting the appropriate settings in your browser.

## Personal Information

We do not collect personally identifiable information through Google Analytics. Any personally identifiable information, such as your name and email address, would only be collected if voluntarily submitted for specific educational purposes (e.g., feedback or course-related inquiries). We will never sell or distribute your personal information to third parties.

For any questions or concerns, please contact grace<-at->stat.ubc.ca.